model_name_or_path: /remote-home1/share/models/Qwen/Qwen2.5-0.5B-Instruct/
trust_remote_code: True
stage: sft
do_train: True
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json
dataset: search_sft_data
dataset_dir: /remote-home1/bwang/hw4/LLaMA-Factory/data
template: qwen
cutoff_len: 2048
max_samples: 1000
overwrite_cache: True
preprocessing_num_workers: 1
dataloader_num_workers: 1
output_dir: saves/qwen2.5-0.5b/full/sft
logging_steps: 10
save_steps: 500
plot_loss: True
overwrite_output_dir: True
save_only_model: False
report_to: none
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 1e-05
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: True
ddp_timeout: 180000000
resume_from_checkpoint: False
